[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1DB954"
backgroundColor = "#F7F8F3"
secondaryBackgroundColor = "#E9F2E3"
textColor = "#111111"
